name: "Controls - Terraform Destroy"

on:
  workflow_call:
    secrets:
      TF_API_TOKEN:
        required: true
        
env:
  TF_CLOUD_ORGANIZATION: "CCC-Testing"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}" # API Token for Project
  TF_WORKSPACE: "ccc-controls-testing" #TODO: TBD
  CONFIG_DIRECTORY: "./src/control-catalog/terraform_modules"

jobs:
    terraform:
      name: "Terraform Destroy"
      runs-on: ubuntu-latest
      permissions:
        contents: read
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Upload Configuration
          uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.2.0
          id: apply-upload
          with:
            workspace: ${{ env.TF_WORKSPACE }}
            directory: ${{ env.CONFIG_DIRECTORY }}
  
        - name: Create Destroy Run
          uses: hashicorp/tfc-workflows-github/actions/create-run@v1.2.0
          id: apply-run
          with:
            workspace: ${{ env.TF_WORKSPACE }}
            configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}
            is_destroy: True
  
        - name: Apply
          uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.2.0
          if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable
          id: apply
          with:
            run: ${{ steps.apply-run.outputs.run_id }}
            comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"