name: Lint Checks

on:
  workflow_call:

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Markdown Lint Against Codebase
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          config: './.markdownlint-cli2.yaml'
          globs: '**/*.md'