name: "PR Workflow"

on:
  pull_request:
  workflow_dispatch:

jobs:
  link-checker:
        uses: ./.github/workflows/links.yml
        permissions:
          pull-requests: write
          contents: read
