name: TODO Checker

on:
    workflow_call:

jobs:
  find-todos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for TODOs in services directory         
        uses: damienjburks/simple-todo-checker@0.1.3-alpha
        with: 
          path: "./services"
    